# This workflow runs SDK related jobs for OpenMLDB
name: SDK

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  go-sdk:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v4
        with:
          go-version: '^1.18'

      - name: OpenMLDB cluster
        run: |
          docker compose -f docker-compose.yml up -d

      - name: init test database
        env:
          OPENMLDB_NS_HOST: 127.0.0.1
          OPENMLDB_NS_PORT: 6527
        run: |
          echo "CREATE DATABASE test_db;" | ./openmldb/bin/openmldb --host=$OPENMLDB_NS_HOST --port=$OPENMLDB_NS_PORT
          docker compose -f docker-compose.yml exec ?

      - name: go test
        env:
          OPENMLDB_APISERVER_HOST: 127.0.0.1
          OPENMLDB_APISERVER_PORT: 9527
        run: go test ./... -race -covermode=atomic -coverprofile=coverage.out

      - name: Coverage
        uses: codecov/codecov-action@v4
        with:
          files: go/coverage.out
          fail_ci_if_error: true
          verbose: true
